In [1]:
import MetaTrader5 as mt5
import pandas as pd
import plotly.graph_objects as go
import datetime as dt
from datetime import datetime

In [2]:
mt5.initialize()

True

In [83]:
timeframe=mt5.TIMEFRAME_H1
symbol = "EURUSD"
number_of_data = 600
PIP_LOCATION = 1e-5

In [84]:
from_date = datetime.now()
# Extract n Ticks before now
rates = mt5.copy_rates_from(symbol, timeframe, from_date, number_of_data)
# Transform Tuple into a DataFrame
df_rates = pd.DataFrame(rates)
df_rates["time"] = pd.to_datetime(df_rates["time"], unit="s")

In [85]:
df_rates.rename(columns={
    'close' : 'bid_c',
    'open' : 'bid_o',
    'high' : 'bid_h',
    'low' : 'bid_l',
}, inplace=True)

In [86]:
ask_h_list = []
ask_l_list = []
ask_o_list = []
ask_c_list = []
spread_list = []
for i,t in enumerate(df_rates.time):
    ticks = mt5.copy_ticks_range(symbol,t,t+ dt.timedelta(hours=1),mt5.COPY_TICKS_ALL )
    df_ticks = pd.DataFrame(ticks)
#     print(df_ticks)
#     df_ticks["time"] = pd.to_datetime(df_ticks["time"], unit="s")
    df_ticks['spread'] = df_ticks.ask-df_ticks.bid
    ask_h = df_ticks.ask.max()
    ask_l = df_ticks.ask.min()
    ask_o = df_ticks.ask.iloc[0]
    ask_c = df_ticks.ask.iloc[-1]
    ask_h_list += [ask_h]
    ask_l_list += [ask_l]
    ask_o_list += [ask_o]
    ask_c_list += [ask_c]
    spread_list += [df_ticks['spread'].max()]

In [81]:
df_rates['ask_h'] = ask_h_list
df_rates['ask_l'] = ask_l_list
df_rates['ask_o'] = ask_o_list
df_rates['ask_c'] = ask_c_list
df_rates.spread = spread_list

df_rates['mid_h'] = (df_rates.ask_h + df_rates.bid_h)/2
df_rates['mid_l'] = (df_rates.ask_l + df_rates.bid_l)/2
df_rates['mid_o'] = (df_rates.ask_o + df_rates.bid_o)/2
df_rates['mid_c'] = (df_rates.ask_c + df_rates.bid_c)/2

In [82]:
df_rates

,time,bid_o,bid_h,bid_l,bid_c,tick_volume,spread,real_volume,ask_h,ask_l,ask_o,ask_c,mid_h,mid_l,mid_o,mid_c
0,2023-02-17 20:00:00,1.06786,1.06906,1.06775,1.06856,3136,0.00004,0,1.06909,1.06777,1.06786,1.06858,1.069075,1.067760,1.067860,1.068570
1,2023-02-17 21:00:00,1.06855,1.06969,1.06853,1.06963,3092,0.00004,0,1.06971,1.06855,1.06857,1.06963,1.069700,1.068540,1.068560,1.069630
2,2023-02-17 22:00:00,1.06963,1.06984,1.06935,1.06946,3008,0.00005,0,1.06985,1.06936,1.06963,1.06947,1.069845,1.069355,1.069630,1.069465
3,2023-02-17 23:00:00,1.06946,1.06978,1.06927,1.06936,808,0.00007,0,1.06979,1.06929,1.06949,1.06941,1.069785,1.069280,1.069475,1.069385
4,2023-02-20 00:00:00,1.06864,1.06931,1.06840,1.06907,1111,0.00068,0,1.06940,1.06885,1.06897,1.06916,1.069355,1.068625,1.068805,1.069115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2023-03-20 12:00:00,1.06744,1.06994,1.06707,1.06959,10992,0.00005,0,1.06995,1.06711,1.06745,1.06959,1.069945,1.067090,1.067445,1.069590
496,2023-03-20 13:00:00,1.06958,1.07088,1.06887,1.07071,7623,0.00005,0,1.07088,1.06889,1.06960,1.07071,1.070880,1.068880,1.069590,1.070710
497,2023-03-20 14:00:00,1.07069,1.07176,1.07015,1.07051,10268,0.00004,0,1.07178,1.07017,1.07069,1.07045,1.071770,1.070160,1.070690,1.070480
498,2023-03-20 15:00:00,1.07050,1.07310,1.07028,1.07237,11080,0.00004,0,1.07310,1.07030,1.07051,1.07239,1.073100,1.070290,1.070505,1.072380
499,2023-03-20 16:00:00,1.07237,1.07296,1.07125,1.07267,9515,0.00005,0,1.07298,1.07126,1.07239,1.07266,1.072970,1.071255,1.072380,1.072665

In [ ]:
from_date

In [ ]:
for t in df_rates.time_str:
    ticks = mt5.copy_ticks_range(symbol,t,t+ dt.timedelta(hours=1),mt5.COPY_TICKS_ALL )

In [ ]:
ticks = mt5.copy_ticks_range(symbol,datetime.fromtimestamp(df_rates.time.iloc[0]),datetime.fromtimestamp(df_rates.time.iloc[1]),mt5.COPY_TICKS_ALL )
df_ticks = pd.DataFrame(ticks)
df_ticks["time"] = pd.to_datetime(df_ticks["time"], unit="s")
df_ticks['spread'] = df_ticks.ask-df_ticks.bid
ask_h = df_ticks.ask.max()
ask_l = df_ticks.ask.min()
ask_o = df_ticks.ask.iloc[0]
ask_c = df_ticks.ask.iloc[-1]

bid_h = df_ticks.bid.max()
bid_l = df_ticks.bid.min()
bid_o = df_ticks.bid.iloc[0]
bid_c = df_ticks.bid.iloc[-1]

In [ ]:
df_ticks.spread.max()//1e-5*1e-5

In [ ]:
mt5.symbol_info_tick(symbol)

In [ ]:
df_ticks.spread.min()

In [ ]:
print(ask_h,ask_l,ask_c,ask_o)

In [ ]:
print(bid_h,bid_l,bid_c,bid_o)

In [ ]:
bid_o-df_rates.open.iloc[0]

In [ ]:
bid_c-df_rates.close.iloc[0]

In [ ]:
bid_h-df_rates.high.iloc[0]

In [ ]:
bid_l-df_rates.low.iloc[0]

In [ ]:
ticks = mt5.copy_ticks_range(symbol,datetime.fromtimestamp(df_rates.time.iloc[1]),datetime.fromtimestamp(df_rates.time.iloc[2]),mt5.COPY_TICKS_ALL )
df_ticks = pd.DataFrame(ticks)
df_ticks["time"] = pd.to_datetime(df_ticks["time"], unit="s")
df_ticks

In [ ]:
ticks = mt5.copy_ticks_range(symbol,datetime.fromtimestamp(df_rates.time.iloc[0]),datetime.fromtimestamp(df_rates.time.iloc[2]),mt5.COPY_TICKS_ALL )
df_ticks = pd.DataFrame(ticks)
df_ticks["time"] = pd.to_datetime(df_ticks["time"], unit="s")
df_ticks

In [ ]:
8155 +5072